name: CI

on:
  push: # on push commits at any branch
  pull_request: # on external PR
  workflow_dispatch: # on demand

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.9' # oldest supported Py3
          - '3' # newest supported Py3
    name: Python ${{ matrix.python-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y libsndfile1 portaudio19-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            pytest-cov
            coveralls

      - name: Unit tests
        run: |
          pytest b2btest_audio

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
